In [34]:
## Numpy uses cpp and c bindings so it is important as the operations become fast. 
## it provides operations for arrays
import numpy as np

In [2]:
l=[1,2,3,4,5]
arr=np.array(l)

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.shape 
## gives number of elements and since it is 1d so there is comma

(5,)

In [21]:
l1=[1,2,2]
l2=[1,2,1]
l3=[1,2,20]
l4=[1,2,21]
arr=np.array([l1,l2,l3,l4])

In [22]:
arr.shape

(4, 3)

In [23]:
arr.reshape(3,4)
## it will give a value error if we give different values like (4,4)

array([[ 1,  2,  2,  1],
       [ 2,  1,  1,  2],
       [20,  1,  2, 21]])

In [26]:
arr[1:,1:]  ## indexing in array (row,column)

array([[ 2,  1],
       [ 2, 20],
       [ 2, 21]])

In [29]:
##inbuilt functions
arr=np.arange(0,10,step=2)  ##just like range function of python
arr

array([0, 2, 4, 6, 8])

In [30]:
np.linspace(1,10,20)  ##for equally spaced values SYNTAX: np.linspace(start,stop,number of points)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [38]:
##copy function and broadcasting
l1=[1,2,3,3,4,5,6]
a1=np.array(l1)
a1[2:]=20
a1

array([ 1,  2, 20, 20, 20, 20, 20])

In [39]:
arr1=a1
arr1[:]=10
arr1

array([10, 10, 10, 10, 10, 10, 10])

In [44]:
a1 ## a1 also changes with arr1 (reference type) to prevent this we have copy()
arr1=a1.copy()
arr1[:]=20
a1


array([10, 10, 10, 10, 10, 10, 10])

In [45]:
## conditions useful in Explanatory data analysis
l1=[1,2,3,3,4,5,6]
arr=np.array(l1)
val=2
arr<2

array([ True, False, False, False, False, False, False])

In [46]:
## if i want elements less than 2 then we can write it inside square braces
arr[arr<2]

array([1])

In [47]:
## it converts elements to 1 SYNTAX: np.ones(no. of elements, dtype) dtype is float by default
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
np.random.rand(3,3) ## this will create a matrix of the given size and the elements will be random values between [0,1)


array([[0.29616614, 0.06876449, 0.66914345],
       [0.93543287, 0.98322426, 0.50995089],
       [0.29387657, 0.64682437, 0.52538254]])

In [51]:
np.random.randint(0,100,8) ##between 0 to 100 any 8 random integers
## we can also create a matrix by passing reshape ()
np.random.randint(0,100,8).reshape(2,4)

array([[ 7, 91, 45,  2],
       [59,  0, 29, 50]])

In [50]:
np.random.random_sample((1,5)) ## returns random floats [0,1)

array([[0.10991179, 0.3499987 , 0.58546789, 0.45019441, 0.20722601]])